/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BdrRouteImport } from './routes/bdr'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as InsideSalesRouteImport } from './routes/inside-sales'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as MentoriaRouteImport } from './routes/mentoria'
import { Route as MetodologiasRouteImport } from './routes/metodologias'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as SdrRouteImport } from './routes/sdr'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin/eventos'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as ApiPublicPlaybookPdfRouteImport } from './routes/api/public/playbook-pdf'
import { Route as ApiPublicCertificateTokenRouteImport } from './routes/api/public/certificate/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BdrRoute = BdrRouteImport.update({
  id: '/bdr',
  path: '/bdr',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const InsideSalesRoute = InsideSalesRouteImport.update({
  id: '/inside-sales',
  path: '/inside-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriaRoute = MentoriaRouteImport.update({
  id: '/mentoria',
  path: '/mentoria',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiasRoute = MetodologiasRouteImport.update({
  id: '/metodologias',
  path: '/metodologias',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const SdrRoute = SdrRouteImport.update({
  id: '/sdr',
  path: '/sdr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/admin/eventos',
    path: '/admin/eventos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlaybookPdfRoute = ApiPublicPlaybookPdfRouteImport.update({
  id: '/api/public/playbook-pdf',
  path: '/api/public/playbook-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCertificateTokenRoute =
  ApiPublicCertificateTokenRouteImport.update({
    id: '/api/public/certificate/$token',
    path: '/api/public/certificate/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bdr': typeof BdrRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/eventos': typeof EventosRoute
  '/inside-sales': typeof InsideSalesRoute
  '/materiais': typeof MateriaisRoute
  '/mentoria': typeof MentoriaRoute
  '/metodologias': typeof MetodologiasRoute
  '/parceiros': typeof ParceirosRoute
  '/sdr': typeof SdrRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/playbook-pdf': typeof ApiPublicPlaybookPdfRoute
  '/api/public/certificate/$token': typeof ApiPublicCertificateTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bdr': typeof BdrRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/eventos': typeof EventosRoute
  '/inside-sales': typeof InsideSalesRoute
  '/materiais': typeof MateriaisRoute
  '/mentoria': typeof MentoriaRoute
  '/metodologias': typeof MetodologiasRoute
  '/parceiros': typeof ParceirosRoute
  '/sdr': typeof SdrRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/playbook-pdf': typeof ApiPublicPlaybookPdfRoute
  '/api/public/certificate/$token': typeof ApiPublicCertificateTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bdr': typeof BdrRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/eventos': typeof EventosRoute
  '/inside-sales': typeof InsideSalesRoute
  '/materiais': typeof MateriaisRoute
  '/mentoria': typeof MentoriaRoute
  '/metodologias': typeof MetodologiasRoute
  '/parceiros': typeof ParceirosRoute
  '/sdr': typeof SdrRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/playbook-pdf': typeof ApiPublicPlaybookPdfRoute
  '/api/public/certificate/$token': typeof ApiPublicCertificateTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bdr'
    | '/diagnostico'
    | '/eventos'
    | '/inside-sales'
    | '/materiais'
    | '/mentoria'
    | '/metodologias'
    | '/parceiros'
    | '/sdr'
    | '/admin/eventos'
    | '/api/public/bootstrap-admin'
    | '/api/public/playbook-pdf'
    | '/api/public/certificate/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bdr'
    | '/diagnostico'
    | '/eventos'
    | '/inside-sales'
    | '/materiais'
    | '/mentoria'
    | '/metodologias'
    | '/parceiros'
    | '/sdr'
    | '/admin/eventos'
    | '/api/public/bootstrap-admin'
    | '/api/public/playbook-pdf'
    | '/api/public/certificate/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bdr'
    | '/diagnostico'
    | '/eventos'
    | '/inside-sales'
    | '/materiais'
    | '/mentoria'
    | '/metodologias'
    | '/parceiros'
    | '/sdr'
    | '/_authenticated/admin/eventos'
    | '/api/public/bootstrap-admin'
    | '/api/public/playbook-pdf'
    | '/api/public/certificate/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BdrRoute: typeof BdrRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EventosRoute: typeof EventosRoute
  InsideSalesRoute: typeof InsideSalesRoute
  MateriaisRoute: typeof MateriaisRoute
  MentoriaRoute: typeof MentoriaRoute
  MetodologiasRoute: typeof MetodologiasRoute
  ParceirosRoute: typeof ParceirosRoute
  SdrRoute: typeof SdrRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicPlaybookPdfRoute: typeof ApiPublicPlaybookPdfRoute
  ApiPublicCertificateTokenRoute: typeof ApiPublicCertificateTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bdr': {
      id: '/bdr'
      path: '/bdr'
      fullPath: '/bdr'
      preLoaderRoute: typeof BdrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inside-sales': {
      id: '/inside-sales'
      path: '/inside-sales'
      fullPath: '/inside-sales'
      preLoaderRoute: typeof InsideSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoria': {
      id: '/mentoria'
      path: '/mentoria'
      fullPath: '/mentoria'
      preLoaderRoute: typeof MentoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologias': {
      id: '/metodologias'
      path: '/metodologias'
      fullPath: '/metodologias'
      preLoaderRoute: typeof MetodologiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdr': {
      id: '/sdr'
      path: '/sdr'
      fullPath: '/sdr'
      preLoaderRoute: typeof SdrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/playbook-pdf': {
      id: '/api/public/playbook-pdf'
      path: '/api/public/playbook-pdf'
      fullPath: '/api/public/playbook-pdf'
      preLoaderRoute: typeof ApiPublicPlaybookPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/certificate/$token': {
      id: '/api/public/certificate/$token'
      path: '/api/public/certificate/$token'
      fullPath: '/api/public/certificate/$token'
      preLoaderRoute: typeof ApiPublicCertificateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BdrRoute: BdrRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EventosRoute: EventosRoute,
  InsideSalesRoute: InsideSalesRoute,
  MateriaisRoute: MateriaisRoute,
  MentoriaRoute: MentoriaRoute,
  MetodologiasRoute: MetodologiasRoute,
  ParceirosRoute: ParceirosRoute,
  SdrRoute: SdrRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicPlaybookPdfRoute: ApiPublicPlaybookPdfRoute,
  ApiPublicCertificateTokenRoute: ApiPublicCertificateTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
