/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as MentoriaRouteImport } from './routes/mentoria'
import { Route as AuthenticatedAdminCursosRouteImport } from './routes/_authenticated/admin/cursos'
import { Route as AuthenticatedAdminEventosRouteImport } from './routes/_authenticated/admin/eventos'
import { Route as ApiPublicBootstrapAdminRouteImport } from './routes/api/public/bootstrap-admin'
import { Route as ApiPublicCertificateTokenRouteImport } from './routes/api/public/certificate/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriaRoute = MentoriaRouteImport.update({
  id: '/mentoria',
  path: '/mentoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCursosRoute =
  AuthenticatedAdminCursosRouteImport.update({
    id: '/admin/cursos',
    path: '/admin/cursos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEventosRoute =
  AuthenticatedAdminEventosRouteImport.update({
    id: '/admin/eventos',
    path: '/admin/eventos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicBootstrapAdminRoute = ApiPublicBootstrapAdminRouteImport.update({
  id: '/api/public/bootstrap-admin',
  path: '/api/public/bootstrap-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCertificateTokenRoute =
  ApiPublicCertificateTokenRouteImport.update({
    id: '/api/public/certificate/$token',
    path: '/api/public/certificate/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/eventos': typeof EventosRoute
  '/mentoria': typeof MentoriaRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/certificate/$token': typeof ApiPublicCertificateTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/eventos': typeof EventosRoute
  '/mentoria': typeof MentoriaRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/certificate/$token': typeof ApiPublicCertificateTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/eventos': typeof EventosRoute
  '/mentoria': typeof MentoriaRoute
  '/_authenticated/admin/cursos': typeof AuthenticatedAdminCursosRoute
  '/_authenticated/admin/eventos': typeof AuthenticatedAdminEventosRoute
  '/api/public/bootstrap-admin': typeof ApiPublicBootstrapAdminRoute
  '/api/public/certificate/$token': typeof ApiPublicCertificateTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diagnostico'
    | '/eventos'
    | '/mentoria'
    | '/admin/cursos'
    | '/admin/eventos'
    | '/api/public/bootstrap-admin'
    | '/api/public/certificate/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/diagnostico'
    | '/eventos'
    | '/mentoria'
    | '/admin/cursos'
    | '/admin/eventos'
    | '/api/public/bootstrap-admin'
    | '/api/public/certificate/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/diagnostico'
    | '/eventos'
    | '/mentoria'
    | '/_authenticated/admin/cursos'
    | '/_authenticated/admin/eventos'
    | '/api/public/bootstrap-admin'
    | '/api/public/certificate/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  EventosRoute: typeof EventosRoute
  MentoriaRoute: typeof MentoriaRoute
  ApiPublicBootstrapAdminRoute: typeof ApiPublicBootstrapAdminRoute
  ApiPublicCertificateTokenRoute: typeof ApiPublicCertificateTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoria': {
      id: '/mentoria'
      path: '/mentoria'
      fullPath: '/mentoria'
      preLoaderRoute: typeof MentoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/cursos': {
      id: '/_authenticated/admin/cursos'
      path: '/admin/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AuthenticatedAdminCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/eventos': {
      id: '/_authenticated/admin/eventos'
      path: '/admin/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AuthenticatedAdminEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap-admin': {
      id: '/api/public/bootstrap-admin'
      path: '/api/public/bootstrap-admin'
      fullPath: '/api/public/bootstrap-admin'
      preLoaderRoute: typeof ApiPublicBootstrapAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/certificate/$token': {
      id: '/api/public/certificate/$token'
      path: '/api/public/certificate/$token'
      fullPath: '/api/public/certificate/$token'
      preLoaderRoute: typeof ApiPublicCertificateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCursosRoute: typeof AuthenticatedAdminCursosRoute
  AuthenticatedAdminEventosRoute: typeof AuthenticatedAdminEventosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCursosRoute: AuthenticatedAdminCursosRoute,
  AuthenticatedAdminEventosRoute: AuthenticatedAdminEventosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  EventosRoute: EventosRoute,
  MentoriaRoute: MentoriaRoute,
  ApiPublicBootstrapAdminRoute: ApiPublicBootstrapAdminRoute,
  ApiPublicCertificateTokenRoute: ApiPublicCertificateTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
